version: 2.1

executors:
  my-executor:
    docker:
      - image: cimg/node:13.8.0

jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - run: echo "BUILD"
      - run: npm i
      - run: npm run lint

  test:
    executor: my-executor
    steps:
      - checkout
      - run: echo "TEST"
      - run: npm i
      - run: npm run test

  analyze:
    executor: my-executor
    steps:
      - checkout
      - run: echo "ANALYZE"
      - run: npm audit

workflows:
  bta:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test


# VS Code Extension Version: 1.3.0